### ISSUE TITLE
use camelCase not CamelCase; use verb in functions

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBESvisualise#17]
use 
`plotSamplingCoverageMap` 
instead of 
`SamplingCoverage`

from style manual [[link](https://github.com/ices-tools-dev/RDBEScore/blob/dev/WGRDBES-EST/newbies_guide/StyleGuide_WKRDB-EST_Annex8.pdf)]
![image](https://github.com/ices-tools-dev/RDBESvisualise/assets/31890653/e440b4ce-1785-46d7-bb22-3c8cdde96155)
see more examples in https://github.com/ices-tools-dev/RDBEScore/R

**Comment by erosquesada** [comment]
Thanks for highlighting it. 
I renamed the most recent version of the function script. 
https://github.com/ices-tools-dev/RDBESvisualise/blob/dev/R/produceSamplingCoverage.R

I used `produceSamplingCoverage` instead of `plotSamplingCoverageMap` as the function aim goes beyond the mapping and even plotting (e.g. will do time-series, will do tables).

**Comment by nmprista** [comment]
nice. closed.
